[profile.default]
src = "src"
out = "out"
libs = ["lib"]
broadcast = 'records'
optimizer = true
optimizer_runs = 999999
solc_version = "0.8.20"
remappings = [
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts',
    "@account-abstraction/=lib/account-abstraction/contracts",
]

